Repository woowa-techcamp-2020/hkb-13, pull requests merged in 2020-08, with the labels that each got.

#25 Feature/nohgijin/refactor
  src/client/apis/getCalendarAPI.js
  src/client/models/hkbModel.js
  src/client/scripts/calendar/Calendar.js
  src/client/scripts/calendar/Day.js
  src/client/scripts/router.js
  src/client/scripts/store/CalendarModel.js
  src/client/scripts/store/Observable.js
Labels: backend

#26 Feature/dnacu/refactor
  src/client/apis/getCalendarAPI.js
  src/client/apis/getReportsListAPI.js
  src/client/models/hkbModel.js
  src/client/scripts/calendar/Calendar.js
  src/client/scripts/calendar/Day.js
  src/client/scripts/navigation/navigation.js
  src/client/scripts/reportsList/ReportsList.js
  src/client/scripts/reportsList/report.js
  src/client/scripts/reportsList/reportsList.js
  src/client/scripts/router.js
  src/client/scripts/store/CalendarModel.js
  src/client/scripts/store/Observable.js
  src/client/utils/parsers.js
  src/client/views/formModal.html
  src/server/controller/reportsList.js
  src/server/model/reportsList.js
  src/server/router/reportsList.js
Labels: frontend, refactor

#30 Feature/dnacu/refactor
  src/client/models/hkbModel.js
  src/client/scripts/calendar/Calendar.js
  src/client/scripts/navigation/Navigation.js
  src/client/scripts/navigation/navigation.js
  src/client/scripts/reportsList/ReportsList.js
  src/client/scripts/router.js
  src/client/utils/parsers.js
  src/server/app.js
  src/server/router/index.js
  src/server/router/report.js
Labels: frontend, refactor

#32 Feature/nohgijin/login
  .gitignore
  package-lock.json
  package.json
  src/client/scripts/login/Login.js
  src/client/scripts/router.js
  src/server/app.js
  src/server/router/index.js
  src/server/router/login.js
Labels: backend

#33 Feature/nohgijin/calendar checkbox
  src/client/scripts/calendar/Calendar.js
  src/client/scripts/login/Login.js
  src/client/styles/components/calendar.scss
Labels: frontend

#34 Feature/nohgijin/calendar checkbox
  src/client/scripts/calendar/Calendar.js
  src/client/scripts/login/Login.js
  src/client/styles/components/calendar.scss
  src/server/router/login.js
Labels: frontend

#36 feat: 현재 날짜 표시
  src/client/scripts/calendar/Day.js
  src/client/styles/components/calendar.scss
Labels: frontend

#37 Feature/dnacu/refactor
  src/client/models/hkbModel.js
  src/client/scripts/calendar/Calendar.js
  src/client/scripts/navigation/Navigation.js
  src/client/scripts/notFound/notFound.js
  src/client/scripts/reportsList/ReportsList.js
  src/client/scripts/router.js
  src/client/styles/components/notFound.scss
  src/client/styles/globalstyle.scss
Labels: frontend, refactor

#38 Feature/dnacu/reports list
  src/client/apis/createAReportAPI.js
  src/client/apis/getReportsListAPI.js
  src/client/apis/index.js
  src/client/apis/modifyAReportAPI.js
  src/client/apis/removeAReportAPI.js
  src/client/models/hkbModel.js
  src/client/scripts/reportsList/AddReportModal.js
  src/client/scripts/reportsList/EditReportModal.js
  src/client/scripts/reportsList/ReportsList.js
  src/client/scripts/reportsList/report.js
  src/client/styles/components/formModal.scss
  src/client/styles/components/reportsList.scss
  src/server/model/reportsList.js
Labels: feat:reportsList, frontend

#39 Feature/nohgijin/login
  .gitignore
  .vscode/settings.json
  package-lock.json
  package.json
  src/client/apis/createAReportAPI.js
  src/client/apis/getCalendarAPI.js
  src/client/apis/getReportsListAPI.js
  src/client/apis/modifyAReportAPI.js
  src/client/apis/removeAReportAPI.js
  src/client/scripts/login/Login.js
  src/client/scripts/navigation/Navigation.js
  src/client/scripts/router.js
  src/client/styles/components/login.scss
  src/client/styles/globalstyle.scss
  src/client/utils/lit.js
  src/client/views/index.html
  src/server/app.js
  src/server/controller/calendar.js
  src/server/controller/reportsList.js
  src/server/model/login.js
  src/server/router/calendar.js
  src/server/router/ensureAuth.js
  src/server/router/index.js
  src/server/router/login.js
  src/server/router/logout.js
  src/server/router/report.js
Labels: api, backend, frontend

#43 refactor: 코드리뷰 바탕으로 수정
  src/client/scripts/login/Login.js
  src/client/utils/constants.js
  src/config/githubPassport.example.js
  src/config/googlePassport.example.js
  src/config/naverPassport.example.js
  src/server/model/category.js
  src/server/model/login.js
  src/server/model/payment.js
  src/server/router/login.js
  src/server/router/loginGithub.js
  src/server/router/loginGoogle.js
  src/server/router/loginNaver.js
Labels: backend, enhancement

#44 Feature/dnacu/statistics
  src/client/models/hkbModel.js
  src/client/scripts/navigation/Navigation.js
  src/client/scripts/reportsList/AddReportModal.js
  src/client/scripts/reportsList/EditReportModal.js
  src/client/scripts/reportsList/ReportsList.js
  src/client/scripts/reportsList/pieChart.js
  src/client/scripts/reportsList/report.js
  src/client/scripts/router.js
  src/client/scripts/statistics/Statistics.js
  src/client/scripts/statistics/barChart.js
  src/client/scripts/statistics/pieChart.js
  src/client/styles/components/navigation.scss
  src/client/styles/components/reportsList.scss
  src/client/styles/components/statistics.scss
  src/client/styles/globalstyle.scss
  src/client/utils/lit.js
Labels: frontend

#45 Feature/dnacu/statistics
  src/client/apis/index.js
  src/client/apis/statisticsAPI.js
  src/client/models/hkbModel.js
  src/client/scripts/login/Login.js
  src/client/scripts/statistics/barChart.js
  src/client/styles/components/login.scss
  src/server/app.js
  src/server/controller/statistics.js
  src/server/model/statistics.js
  src/server/router/index.js
  src/server/router/statistics.js
Labels: api, backend, frontend

#47 feat: pie chart legend 구현
  src/client/scripts/statistics/pieChart.js
  src/client/styles/components/statistics.scss
  src/client/styles/globalstyle.scss
Labels: frontend

#48 Feature/nohgijin/line chart
  src/client/scripts/calendar/Month.js
  src/client/scripts/statistics/Statistics.js
  src/client/scripts/statistics/lineChart.js
  src/server/model/calendar.js
Labels: bug, frontend
