Repository woowa-techcamp-2020/hkb-13, pull requests merged in 2020-07, with the labels that each got.

#5 Feature/nohgijin/calendar
  .gitignore
  .prettierrc
  .vscode/settings.json
  babel.config.js
  jsconfig.json
  package-lock.json
  package.json
  src/app.js
  src/client/index.js
  src/client/scripts/calendar/Calendar.js
  src/client/scripts/calendar/Day.js
  src/client/scripts/calendar/Month.js
  src/client/utils/constants.js
  src/client/views/index.html
  webpack.config.js
Labels: frontend

#7 Feature/dnacu/history
  src/client/index.js
  src/client/scripts/reportsList/pieChart.js
  src/client/styles/components/formModal.scss
  src/client/styles/components/header.scss
  src/client/styles/components/navigation.scss
  src/client/styles/components/reportsList.scss
  src/client/styles/components/svgs.scss
  src/client/styles/fonts.scss
  src/client/styles/globalstyle.scss
  src/client/utils/constants.js
  src/client/views/formModal.html
  src/client/views/index.html
  src/client/views/reportsList.html
  src/client/views/statistics.html
  webpack.config.js
Labels: frontend, markup

#8 Feature/nohgijin/calendar
  src/client/scripts/calendar/Calendar.js
  src/client/scripts/calendar/Day.js
  src/client/styles/components/calendar.scss
  src/client/utils/constants.js
  src/client/views/app.html
  src/client/views/index.html
Labels: frontend

#10 Feature/nohgijin/calendar
  src/client/scripts/calendar/Calendar.js
  src/client/scripts/calendar/Day.js
  src/client/utils/constants.js
  src/client/views/index.html
Labels: frontend, markup

#15 Feature/nohgijin/calendar division
  src/client/index.js
  src/client/scripts/calendar/Calendar.js
  src/client/scripts/calendar/Day.js
  src/client/scripts/calendar/Month.js
  src/client/scripts/calendar/dummy.js
  src/client/scripts/route/router.js
  src/client/styles/components/calendar.scss
  src/client/styles/globalstyle.scss
  src/client/utils/constants.js
  src/client/utils/html-generator.js
  src/client/views/index.html
  src/server/app.js
Labels: frontend

#17 Feature/nohgijin/calendar division
  src/client/scripts/calendar/Calendar.js
  src/client/scripts/calendar/Day.js
  src/client/scripts/calendar/Month.js
  src/client/scripts/calendar/dummy.js
  src/client/scripts/route/router.js
  src/client/styles/components/calendar.scss
  src/client/styles/components/navigation.scss
  src/client/styles/globalstyle.scss
  src/client/views/index.html
  src/server/controller/reportsList.js
Labels: frontend, markup

#19 Feature/nohgijin/calendar router
  src/client/scripts/calendar/Calendar.js
  src/client/scripts/calendar/Day.js
  src/client/scripts/calendar/Month.js
  src/client/scripts/calendar/dummy.js
  src/client/scripts/navigation/navigation.js
  src/config/index.example.js
  src/server/app.js
  src/server/controller/calendar.js
  src/server/model/calendar.js
  src/server/router/calendar.js
  src/server/router/index.js
  src/server/router/reportsList.js
Labels: api, backend

#20 Client Router에 year, month 추가
  src/client/scripts/calendar/Calendar.js
  src/client/scripts/navigation/navigation.js
  src/client/scripts/router.js
  src/client/utils/htmlGenerator.js
  src/client/utils/urlParser.js
  src/server/model/reportsList.js
  webpack.config.js
Labels: enhancement, frontend

#22 Feature/nohgijin/observer class
  src/client/scripts/calendar/Calendar.js
  src/client/scripts/calendar/Day.js
  src/client/scripts/calendar/Month.js
  src/client/scripts/navigation/navigation.js
  src/client/scripts/store/CalendarModel.js
  src/client/scripts/store/Observable.js
  src/client/utils/comma.js
  src/client/views/statistics.html
  src/server/controller/calendar.js
  src/server/model/calendar.js
  src/server/router/calendar.js
Labels: api, backend

#24 Feature/dnacu/reports list
  src/client/apis/getReportsListAPI.js
  src/client/scripts/navigation/navigation.js
  src/client/scripts/notFound/notFound.js
  src/client/scripts/reportsList/reportsList.js
  src/client/scripts/router.js
  src/client/styles/components/navigation.scss
  src/client/styles/components/reportsList.scss
Labels: api, backend
